/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Medicine.FrontEnd;

import javax.swing.JFrame;

/**
 *
 * @author Apirak Oulis
 */
public class P_LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public P_LOGIN() {
        initComponents();
        this.setLocationRelativeTo(null); // set center on my screen 
        REGISTER_LAYER.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TAB_WINDOW = new javax.swing.JPanel();
        B_MINIMIZE = new javax.swing.JButton();
        B_EXIT = new javax.swing.JButton();
        LOGIN_LAYER = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        TEXT_LOGIN = new javax.swing.JLabel();
        BOX_User = new javax.swing.JTextField();
        BOX_PW = new javax.swing.JPasswordField();
        Button_LOGIN = new javax.swing.JButton();
        Button_CANCLE = new javax.swing.JButton();
        BUTTON = new javax.swing.JPanel();
        jButton_Register = new javax.swing.JButton();
        BG_bottom = new javax.swing.JLabel();
        REGISTER_LAYER = new javax.swing.JPanel();
        TEXT_LOGIN1 = new javax.swing.JLabel();
        TEXT_USER = new javax.swing.JLabel();
        BOX_REG_USER = new javax.swing.JTextField();
        TEXT_PASSWORD = new javax.swing.JLabel();
        BOX_ID2 = new javax.swing.JTextField();
        TEXT_CPASSWORD = new javax.swing.JLabel();
        BOX_ID3 = new javax.swing.JTextField();
        TEXT_NAME = new javax.swing.JLabel();
        BOX_ID4 = new javax.swing.JTextField();
        TEXT_LNAME = new javax.swing.JLabel();
        BOX_ID5 = new javax.swing.JTextField();
        TEXT_AGE = new javax.swing.JLabel();
        BOX_ID6 = new javax.swing.JTextField();
        TEXT_EMAIL = new javax.swing.JLabel();
        BOX_ID7 = new javax.swing.JTextField();
        jButton_backlogin = new javax.swing.JButton();
        Regis_For_Admin = new javax.swing.JCheckBox();
        Regis_For_User = new javax.swing.JCheckBox();
        TEXT_EMAIL1 = new javax.swing.JLabel();
        Combo_box_GENDER = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TEXT_ADDRESS = new javax.swing.JLabel();
        PIC_LEFT = new javax.swing.JPanel();
        GIF_0 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/Asset 2.png"))); // NOI18N

        setTitle("LOGIN");
        setBounds(new java.awt.Rectangle(60, 122, 60, 122));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 650));
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                formAncestorResized(evt);
            }
        });
        getContentPane().setLayout(null);

        TAB_WINDOW.setBackground(new java.awt.Color(60, 63, 75));
        TAB_WINDOW.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        B_MINIMIZE.setBackground(new java.awt.Color(60, 63, 75));
        B_MINIMIZE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/min1.png"))); // NOI18N
        B_MINIMIZE.setToolTipText("Minimize");
        B_MINIMIZE.setBorder(null);
        B_MINIMIZE.setBorderPainted(false);
        B_MINIMIZE.setContentAreaFilled(false);
        B_MINIMIZE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        B_MINIMIZE.setDefaultCapable(false);
        B_MINIMIZE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B_MINIMIZE.setIconTextGap(0);
        B_MINIMIZE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/icons8_Minus_30px_3.png"))); // NOI18N
        B_MINIMIZE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MINIMIZEActionPerformed(evt);
            }
        });

        B_EXIT.setBackground(new java.awt.Color(60, 63, 75));
        B_EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/cancle1.png"))); // NOI18N
        B_EXIT.setToolTipText("Close");
        B_EXIT.setBorder(null);
        B_EXIT.setBorderPainted(false);
        B_EXIT.setContentAreaFilled(false);
        B_EXIT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        B_EXIT.setDefaultCapable(false);
        B_EXIT.setIconTextGap(0);
        B_EXIT.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/cancle2.png"))); // NOI18N
        B_EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TAB_WINDOWLayout = new javax.swing.GroupLayout(TAB_WINDOW);
        TAB_WINDOW.setLayout(TAB_WINDOWLayout);
        TAB_WINDOWLayout.setHorizontalGroup(
            TAB_WINDOWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TAB_WINDOWLayout.createSequentialGroup()
                .addContainerGap(620, Short.MAX_VALUE)
                .addComponent(B_MINIMIZE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(B_EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TAB_WINDOWLayout.setVerticalGroup(
            TAB_WINDOWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TAB_WINDOWLayout.createSequentialGroup()
                .addGroup(TAB_WINDOWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_MINIMIZE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(TAB_WINDOW);
        TAB_WINDOW.setBounds(0, 0, 700, 30);

        LOGIN_LAYER.setBackground(new java.awt.Color(51, 51, 51));
        LOGIN_LAYER.setAlignmentX(0.0F);
        LOGIN_LAYER.setAlignmentY(0.0F);
        LOGIN_LAYER.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LOGO.setDisplayedMnemonic('{');
            LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/giphy.gif"))); // NOI18N
            LOGO.setAlignmentY(0.0F);
            LOGO.setAutoscrolls(true);
            LOGO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            LOGO.setInheritsPopupMenu(false);
            LOGO.setMaximumSize(new java.awt.Dimension(280, 200));
            LOGO.setMinimumSize(new java.awt.Dimension(180, 200));
            LOGO.setName(""); // NOI18N
            LOGO.setPreferredSize(new java.awt.Dimension(420, 140));

            TEXT_LOGIN.setBackground(new java.awt.Color(153, 153, 153));
            TEXT_LOGIN.setDisplayedMnemonic('5');
            TEXT_LOGIN.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
            TEXT_LOGIN.setForeground(new java.awt.Color(79, 182, 210));
            TEXT_LOGIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            TEXT_LOGIN.setText("~ LOGIN ~");
            TEXT_LOGIN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

            BOX_User.setBackground(new java.awt.Color(51, 51, 51));
            BOX_User.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
            BOX_User.setForeground(new java.awt.Color(255, 255, 255));
            BOX_User.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            BOX_User.setText("ascascasc");
            BOX_User.setToolTipText("User ID");
            BOX_User.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true), " User ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(255, 153, 153))); // NOI18N
            BOX_User.setCaretColor(new java.awt.Color(0, 0, 0));
            BOX_User.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            BOX_User.setDisabledTextColor(new java.awt.Color(0, 0, 0));
            BOX_User.setFocusAccelerator(' ');
            BOX_User.setVerifyInputWhenFocusTarget(false);
            BOX_User.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BOX_UserActionPerformed(evt);
                }
            });

            BOX_PW.setBackground(new java.awt.Color(51, 51, 51));
            BOX_PW.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
            BOX_PW.setForeground(new java.awt.Color(255, 255, 255));
            BOX_PW.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            BOX_PW.setText("12211212");
            BOX_PW.setToolTipText("PASSWORD");
            BOX_PW.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 2, true), " Password ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(0, 204, 102))); // NOI18N
            BOX_PW.setCaretColor(new java.awt.Color(0, 0, 0));
            BOX_PW.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            BOX_PW.setDisabledTextColor(new java.awt.Color(0, 0, 0));
            BOX_PW.setFocusAccelerator('6');
            BOX_PW.setName(""); // NOI18N
            BOX_PW.setSelectedTextColor(new java.awt.Color(255, 255, 255));
            BOX_PW.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BOX_PWActionPerformed(evt);
                }
            });

            Button_LOGIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/B_login1.png"))); // NOI18N
            Button_LOGIN.setBorder(null);
            Button_LOGIN.setBorderPainted(false);
            Button_LOGIN.setContentAreaFilled(false);
            Button_LOGIN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            Button_LOGIN.setDefaultCapable(false);
            Button_LOGIN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            Button_LOGIN.setIconTextGap(-2);
            Button_LOGIN.setMaximumSize(new java.awt.Dimension(16, 32));
            Button_LOGIN.setMinimumSize(new java.awt.Dimension(16, 32));
            Button_LOGIN.setPreferredSize(new java.awt.Dimension(160, 30));
            Button_LOGIN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/B_login2.png"))); // NOI18N
            Button_LOGIN.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    Button_LOGINMouseClicked(evt);
                }
            });
            Button_LOGIN.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Button_LOGINActionPerformed(evt);
                }
            });

            Button_CANCLE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/B_cancle1.png"))); // NOI18N
            Button_CANCLE.setBorder(null);
            Button_CANCLE.setBorderPainted(false);
            Button_CANCLE.setContentAreaFilled(false);
            Button_CANCLE.setDefaultCapable(false);
            Button_CANCLE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            Button_CANCLE.setIconTextGap(0);
            Button_CANCLE.setPreferredSize(new java.awt.Dimension(160, 30));
            Button_CANCLE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/B_cancle2.png"))); // NOI18N
            Button_CANCLE.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    Button_CANCLEMouseClicked(evt);
                }
            });
            Button_CANCLE.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Button_CANCLEActionPerformed(evt);
                }
            });

            BUTTON.setDoubleBuffered(false);
            BUTTON.setFont(new java.awt.Font("Serithai", 0, 12)); // NOI18N
            BUTTON.setOpaque(false);

            jButton_Register.setFont(new java.awt.Font("Serithai", 1, 18)); // NOI18N
            jButton_Register.setForeground(new java.awt.Color(255, 255, 255));
            jButton_Register.setText("create new account >> click");
            jButton_Register.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
            jButton_Register.setBorderPainted(false);
            jButton_Register.setContentAreaFilled(false);
            jButton_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jButton_Register.setOpaque(true);
            jButton_Register.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/BG_LOGIN.png"))); // NOI18N
            jButton_Register.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/GIF1.gif"))); // NOI18N
            jButton_Register.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton_RegisterMouseClicked(evt);
                }
            });
            jButton_Register.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_RegisterActionPerformed(evt);
                }
            });

            BG_bottom.setBackground(new java.awt.Color(51, 51, 51));
            BG_bottom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            BG_bottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/++++.png"))); // NOI18N
            BG_bottom.setVerticalAlignment(javax.swing.SwingConstants.TOP);
            BG_bottom.setDisabledIcon(null);
            BG_bottom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            BG_bottom.setIconTextGap(0);
            BG_bottom.setOpaque(true);
            BG_bottom.setRequestFocusEnabled(false);
            BG_bottom.setVerifyInputWhenFocusTarget(false);

            javax.swing.GroupLayout BUTTONLayout = new javax.swing.GroupLayout(BUTTON);
            BUTTON.setLayout(BUTTONLayout);
            BUTTONLayout.setHorizontalGroup(
                BUTTONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BUTTONLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(BUTTONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BG_bottom, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            );
            BUTTONLayout.setVerticalGroup(
                BUTTONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BUTTONLayout.createSequentialGroup()
                    .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                    .addComponent(BG_bottom, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            javax.swing.GroupLayout LOGIN_LAYERLayout = new javax.swing.GroupLayout(LOGIN_LAYER);
            LOGIN_LAYER.setLayout(LOGIN_LAYERLayout);
            LOGIN_LAYERLayout.setHorizontalGroup(
                LOGIN_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGIN_LAYERLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LOGIN_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BOX_PW, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BOX_User, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(85, 85, 85))
                .addGroup(LOGIN_LAYERLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Button_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Button_CANCLE, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(TEXT_LOGIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LOGIN_LAYERLayout.createSequentialGroup()
                    .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            LOGIN_LAYERLayout.setVerticalGroup(
                LOGIN_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGIN_LAYERLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(TEXT_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36)
                    .addComponent(BOX_User, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(BOX_PW, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addGroup(LOGIN_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_CANCLE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                    .addComponent(BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            getContentPane().add(LOGIN_LAYER);
            LOGIN_LAYER.setBounds(280, 30, 420, 620);

            REGISTER_LAYER.setBackground(new java.awt.Color(51, 51, 51));
            REGISTER_LAYER.setForeground(new java.awt.Color(255, 255, 255));
            REGISTER_LAYER.setAlignmentX(0.0F);
            REGISTER_LAYER.setAlignmentY(0.0F);
            REGISTER_LAYER.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            REGISTER_LAYER.setDoubleBuffered(false);
            REGISTER_LAYER.setEnabled(false);
            REGISTER_LAYER.setInheritsPopupMenu(true);

            TEXT_LOGIN1.setBackground(new java.awt.Color(153, 153, 153));
            TEXT_LOGIN1.setDisplayedMnemonic('5');
            TEXT_LOGIN1.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
            TEXT_LOGIN1.setForeground(new java.awt.Color(79, 182, 210));
            TEXT_LOGIN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            TEXT_LOGIN1.setText("~ REGISTER ~");
            TEXT_LOGIN1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
            TEXT_LOGIN1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

            TEXT_USER.setBackground(new java.awt.Color(187, 187, 187));
            TEXT_USER.setFont(new java.awt.Font("Serithai", 1, 20)); // NOI18N
            TEXT_USER.setForeground(new java.awt.Color(255, 255, 255));
            TEXT_USER.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            TEXT_USER.setText("User  :");

            BOX_REG_USER.setBackground(new java.awt.Color(51, 51, 51));
            BOX_REG_USER.setFont(new java.awt.Font("Serithai", 0, 20)); // NOI18N
            BOX_REG_USER.setForeground(new java.awt.Color(255, 255, 255));
            BOX_REG_USER.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            BOX_REG_USER.setText("sdfsd");
            BOX_REG_USER.setToolTipText("Enter Your ID");
            BOX_REG_USER.setActionCommand("<Not Set>");
            BOX_REG_USER.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 1, 1, 5, new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/BG_LOGIN.png")))); // NOI18N
            BOX_REG_USER.setCaretColor(new java.awt.Color(255, 255, 255));
            BOX_REG_USER.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            BOX_REG_USER.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
            BOX_REG_USER.setMargin(new java.awt.Insets(10, 0, 2, 2));
            BOX_REG_USER.setName("scsc"); // NOI18N
            BOX_REG_USER.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BOX_REG_USERActionPerformed(evt);
                }
            });

            TEXT_PASSWORD.setBackground(new java.awt.Color(187, 187, 187));
            TEXT_PASSWORD.setFont(new java.awt.Font("Serithai", 1, 20)); // NOI18N
            TEXT_PASSWORD.setForeground(new java.awt.Color(255, 255, 255));
            TEXT_PASSWORD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            TEXT_PASSWORD.setText("Password  :");

            BOX_ID2.setBackground(new java.awt.Color(51, 51, 51));
            BOX_ID2.setFont(new java.awt.Font("Serithai", 0, 20)); // NOI18N
            BOX_ID2.setForeground(new java.awt.Color(255, 255, 255));
            BOX_ID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            BOX_ID2.setText("dsf");
            BOX_ID2.setToolTipText("Enter Your ID");
            BOX_ID2.setActionCommand("<Not Set>");
            BOX_ID2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 1, 1, 5, new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/BG_LOGIN.png")))); // NOI18N
            BOX_ID2.setCaretColor(new java.awt.Color(255, 255, 255));
            BOX_ID2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            BOX_ID2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
            BOX_ID2.setName("scsc"); // NOI18N
            BOX_ID2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BOX_ID2ActionPerformed(evt);
                }
            });

            TEXT_CPASSWORD.setBackground(new java.awt.Color(187, 187, 187));
            TEXT_CPASSWORD.setFont(new java.awt.Font("Serithai", 1, 20)); // NOI18N
            TEXT_CPASSWORD.setForeground(new java.awt.Color(255, 255, 255));
            TEXT_CPASSWORD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            TEXT_CPASSWORD.setText("Password  :");

            BOX_ID3.setBackground(new java.awt.Color(51, 51, 51));
            BOX_ID3.setFont(new java.awt.Font("Serithai", 0, 20)); // NOI18N
            BOX_ID3.setForeground(new java.awt.Color(255, 255, 255));
            BOX_ID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            BOX_ID3.setText("sdfsdf");
            BOX_ID3.setToolTipText("Enter Your ID");
            BOX_ID3.setActionCommand("<Not Set>");
            BOX_ID3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 1, 1, 5, new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/BG_LOGIN.png")))); // NOI18N
            BOX_ID3.setCaretColor(new java.awt.Color(255, 255, 255));
            BOX_ID3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            BOX_ID3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
            BOX_ID3.setName("scsc"); // NOI18N
            BOX_ID3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BOX_ID3ActionPerformed(evt);
                }
            });

            TEXT_NAME.setBackground(new java.awt.Color(187, 187, 187));
            TEXT_NAME.setFont(new java.awt.Font("Serithai", 1, 20)); // NOI18N
            TEXT_NAME.setForeground(new java.awt.Color(255, 255, 255));
            TEXT_NAME.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            TEXT_NAME.setText("Name  :");

            BOX_ID4.setBackground(new java.awt.Color(51, 51, 51));
            BOX_ID4.setFont(new java.awt.Font("Serithai", 0, 20)); // NOI18N
            BOX_ID4.setForeground(new java.awt.Color(255, 255, 255));
            BOX_ID4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            BOX_ID4.setText("sdf");
            BOX_ID4.setToolTipText("Enter Your ID");
            BOX_ID4.setActionCommand("<Not Set>");
            BOX_ID4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 1, 1, 5, new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/BG_LOGIN.png")))); // NOI18N
            BOX_ID4.setCaretColor(new java.awt.Color(255, 255, 255));
            BOX_ID4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            BOX_ID4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
            BOX_ID4.setName("scsc"); // NOI18N
            BOX_ID4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BOX_ID4ActionPerformed(evt);
                }
            });

            TEXT_LNAME.setBackground(new java.awt.Color(187, 187, 187));
            TEXT_LNAME.setFont(new java.awt.Font("Serithai", 1, 20)); // NOI18N
            TEXT_LNAME.setForeground(new java.awt.Color(255, 255, 255));
            TEXT_LNAME.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            TEXT_LNAME.setText("Last Name  :");

            BOX_ID5.setBackground(new java.awt.Color(51, 51, 51));
            BOX_ID5.setFont(new java.awt.Font("Serithai", 0, 20)); // NOI18N
            BOX_ID5.setForeground(new java.awt.Color(255, 255, 255));
            BOX_ID5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            BOX_ID5.setText("sdfsdf");
            BOX_ID5.setToolTipText("Enter Your ID");
            BOX_ID5.setActionCommand("<Not Set>");
            BOX_ID5.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 1, 1, 5, new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/BG_LOGIN.png")))); // NOI18N
            BOX_ID5.setCaretColor(new java.awt.Color(255, 255, 255));
            BOX_ID5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            BOX_ID5.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
            BOX_ID5.setName("scsc"); // NOI18N
            BOX_ID5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BOX_ID5ActionPerformed(evt);
                }
            });

            TEXT_AGE.setBackground(new java.awt.Color(187, 187, 187));
            TEXT_AGE.setFont(new java.awt.Font("Serithai", 1, 20)); // NOI18N
            TEXT_AGE.setForeground(new java.awt.Color(255, 255, 255));
            TEXT_AGE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            TEXT_AGE.setText("Age  :");

            BOX_ID6.setEditable(false);
            BOX_ID6.setBackground(new java.awt.Color(51, 51, 51));
            BOX_ID6.setFont(new java.awt.Font("Serithai", 0, 20)); // NOI18N
            BOX_ID6.setForeground(new java.awt.Color(255, 255, 255));
            BOX_ID6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            BOX_ID6.setText("sdfsdf");
            BOX_ID6.setToolTipText("Enter Your ID");
            BOX_ID6.setActionCommand("<Not Set>");
            BOX_ID6.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 1, 1, 5, new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/BG_LOGIN.png")))); // NOI18N
            BOX_ID6.setCaretColor(new java.awt.Color(255, 255, 255));
            BOX_ID6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            BOX_ID6.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
            BOX_ID6.setName("scsc"); // NOI18N
            BOX_ID6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BOX_ID6ActionPerformed(evt);
                }
            });

            TEXT_EMAIL.setBackground(new java.awt.Color(187, 187, 187));
            TEXT_EMAIL.setFont(new java.awt.Font("Serithai", 1, 20)); // NOI18N
            TEXT_EMAIL.setForeground(new java.awt.Color(255, 255, 255));
            TEXT_EMAIL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            TEXT_EMAIL.setText("E-mail  :");

            BOX_ID7.setBackground(new java.awt.Color(51, 51, 51));
            BOX_ID7.setFont(new java.awt.Font("Serithai", 0, 20)); // NOI18N
            BOX_ID7.setForeground(new java.awt.Color(255, 255, 255));
            BOX_ID7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            BOX_ID7.setText("p.apirak2000@hotmail.com");
            BOX_ID7.setToolTipText("Enter Your ID");
            BOX_ID7.setActionCommand("<Not Set>");
            BOX_ID7.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 1, 1, 5, new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/BG_LOGIN.png")))); // NOI18N
            BOX_ID7.setCaretColor(new java.awt.Color(255, 255, 255));
            BOX_ID7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            BOX_ID7.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
            BOX_ID7.setFocusAccelerator('1');
            BOX_ID7.setName(""); // NOI18N
            BOX_ID7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BOX_ID7ActionPerformed(evt);
                }
            });

            jButton_backlogin.setFont(new java.awt.Font("Serithai", 1, 20)); // NOI18N
            jButton_backlogin.setForeground(new java.awt.Color(255, 255, 255));
            jButton_backlogin.setText("<< Register >> ");
            jButton_backlogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
            jButton_backlogin.setBorderPainted(false);
            jButton_backlogin.setContentAreaFilled(false);
            jButton_backlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jButton_backlogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/BG_LOGIN.png"))); // NOI18N
            jButton_backlogin.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/GIF1.gif"))); // NOI18N
            jButton_backlogin.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton_backloginMouseClicked(evt);
                }
            });
            jButton_backlogin.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_backloginActionPerformed(evt);
                }
            });

            Regis_For_Admin.setFont(new java.awt.Font("Serithai", 1, 20)); // NOI18N
            Regis_For_Admin.setForeground(new java.awt.Color(255, 255, 255));
            Regis_For_Admin.setMnemonic('h');
            Regis_For_Admin.setSelected(true);
            Regis_For_Admin.setText("Register For Admin");
            Regis_For_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    Regis_For_AdminMouseClicked(evt);
                }
            });
            Regis_For_Admin.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Regis_For_AdminActionPerformed(evt);
                }
            });

            Regis_For_User.setFont(new java.awt.Font("Serithai", 1, 20)); // NOI18N
            Regis_For_User.setForeground(new java.awt.Color(255, 255, 255));
            Regis_For_User.setText("Register For User");
            Regis_For_User.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Regis_For_UserActionPerformed(evt);
                }
            });

            TEXT_EMAIL1.setBackground(new java.awt.Color(187, 187, 187));
            TEXT_EMAIL1.setFont(new java.awt.Font("Serithai", 1, 20)); // NOI18N
            TEXT_EMAIL1.setForeground(new java.awt.Color(255, 255, 255));
            TEXT_EMAIL1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            TEXT_EMAIL1.setText("Gender  :");

            Combo_box_GENDER.setBackground(new java.awt.Color(51, 51, 51));
            Combo_box_GENDER.setFont(new java.awt.Font("Serithai", 1, 20)); // NOI18N
            Combo_box_GENDER.setForeground(new java.awt.Color(255, 255, 255));
            Combo_box_GENDER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
            Combo_box_GENDER.setToolTipText("Cloose Your Gender");
            Combo_box_GENDER.setBorder(null);
            Combo_box_GENDER.setLightWeightPopupEnabled(false);
            Combo_box_GENDER.setOpaque(false);
            Combo_box_GENDER.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Combo_box_GENDERActionPerformed(evt);
                }
            });

            jScrollPane1.setToolTipText("Address");

            jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
            jTextArea1.setColumns(20);
            jTextArea1.setFont(new java.awt.Font("Serithai", 0, 20)); // NOI18N
            jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
            jTextArea1.setLineWrap(true);
            jTextArea1.setRows(5);
            jTextArea1.setTabSize(1);
            jTextArea1.setText("20/96 Nawamin 24 yeak 1");
            jTextArea1.setToolTipText("address");
            jTextArea1.setWrapStyleWord(true);
            jTextArea1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 1, 1, 5, new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/BG_LOGIN.png")))); // NOI18N
            jScrollPane1.setViewportView(jTextArea1);

            TEXT_ADDRESS.setBackground(new java.awt.Color(187, 187, 187));
            TEXT_ADDRESS.setFont(new java.awt.Font("Serithai", 1, 20)); // NOI18N
            TEXT_ADDRESS.setForeground(new java.awt.Color(255, 255, 255));
            TEXT_ADDRESS.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            TEXT_ADDRESS.setText("Address  :");

            javax.swing.GroupLayout REGISTER_LAYERLayout = new javax.swing.GroupLayout(REGISTER_LAYER);
            REGISTER_LAYER.setLayout(REGISTER_LAYERLayout);
            REGISTER_LAYERLayout.setHorizontalGroup(
                REGISTER_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                    .addGroup(REGISTER_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(REGISTER_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                                    .addGroup(REGISTER_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TEXT_CPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TEXT_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TEXT_LNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(TEXT_USER, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BOX_REG_USER, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(TEXT_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(TEXT_AGE, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                                            .addGap(120, 120, 120)
                                            .addGroup(REGISTER_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(BOX_ID2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BOX_ID3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BOX_ID4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BOX_ID5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BOX_ID6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BOX_ID7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(REGISTER_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                                            .addGroup(REGISTER_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(TEXT_ADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TEXT_EMAIL1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(REGISTER_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addComponent(Combo_box_GENDER, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                                            .addGroup(REGISTER_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TEXT_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                                                    .addComponent(Regis_For_Admin)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(Regis_For_User)))
                                            .addGap(0, 9, Short.MAX_VALUE))))))
                        .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(TEXT_LOGIN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REGISTER_LAYERLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton_backlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80))
            );
            REGISTER_LAYERLayout.setVerticalGroup(
                REGISTER_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REGISTER_LAYERLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(TEXT_LOGIN1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(REGISTER_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                            .addComponent(TEXT_USER, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TEXT_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TEXT_CPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TEXT_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TEXT_LNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TEXT_AGE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TEXT_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                            .addComponent(BOX_REG_USER, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BOX_ID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BOX_ID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BOX_ID4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BOX_ID5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BOX_ID6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BOX_ID7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(REGISTER_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TEXT_ADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(REGISTER_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TEXT_EMAIL1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(REGISTER_LAYERLayout.createSequentialGroup()
                            .addComponent(Combo_box_GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)))
                    .addGap(18, 18, 18)
                    .addGroup(REGISTER_LAYERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Regis_For_Admin)
                        .addComponent(Regis_For_User))
                    .addGap(16, 16, 16)
                    .addComponent(jButton_backlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE))
            );

            getContentPane().add(REGISTER_LAYER);
            REGISTER_LAYER.setBounds(280, 30, 420, 620);

            PIC_LEFT.setBackground(new java.awt.Color(57, 57, 57));
            PIC_LEFT.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

            GIF_0.setBackground(new java.awt.Color(255, 255, 255));
            GIF_0.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            GIF_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Medicine/FrontEnd/Images/bglog.png"))); // NOI18N
            GIF_0.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
            GIF_0.setBorder(javax.swing.BorderFactory.createCompoundBorder());

            javax.swing.GroupLayout PIC_LEFTLayout = new javax.swing.GroupLayout(PIC_LEFT);
            PIC_LEFT.setLayout(PIC_LEFTLayout);
            PIC_LEFTLayout.setHorizontalGroup(
                PIC_LEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PIC_LEFTLayout.createSequentialGroup()
                    .addComponent(GIF_0, javax.swing.GroupLayout.PREFERRED_SIZE, 286, Short.MAX_VALUE)
                    .addContainerGap())
            );
            PIC_LEFTLayout.setVerticalGroup(
                PIC_LEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PIC_LEFTLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(GIF_0, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            getContentPane().add(PIC_LEFT);
            PIC_LEFT.setBounds(0, 0, 280, 650);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void formAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorResized
        // TODO add your handling code here:

    }//GEN-LAST:event_formAncestorResized

    private void Button_CANCLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CANCLEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_CANCLEActionPerformed

    private void Button_CANCLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_CANCLEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_CANCLEMouseClicked

    private void Button_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LOGINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_LOGINActionPerformed

    private void Button_LOGINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_LOGINMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_LOGINMouseClicked

    private void BOX_PWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOX_PWActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_BOX_PWActionPerformed

    private void B_EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_B_EXITActionPerformed

    private void B_MINIMIZEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MINIMIZEActionPerformed
        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_B_MINIMIZEActionPerformed

    private void BOX_ID7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOX_ID7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_ID7ActionPerformed

    private void BOX_ID6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOX_ID6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_ID6ActionPerformed

    private void BOX_ID5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOX_ID5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_ID5ActionPerformed

    private void BOX_ID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOX_ID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_ID4ActionPerformed

    private void BOX_ID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOX_ID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_ID3ActionPerformed

    private void BOX_ID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOX_ID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_ID2ActionPerformed

    private void BOX_REG_USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOX_REG_USERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_REG_USERActionPerformed

    private void BOX_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOX_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOX_UserActionPerformed

    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed

        REGISTER_LAYER.setVisible(true);
        LOGIN_LAYER.setVisible(false);

        //        rgt.pack();
        //        rgt.setLocationRelativeTo(null);
        //        rgt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //        this.dispose();
    }//GEN-LAST:event_jButton_RegisterActionPerformed

    private void jButton_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RegisterMouseClicked

    }//GEN-LAST:event_jButton_RegisterMouseClicked

    private void jButton_backloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_backloginMouseClicked
        REGISTER_LAYER.setVisible(false);
        LOGIN_LAYER.setVisible(true);
    }//GEN-LAST:event_jButton_backloginMouseClicked

    private void jButton_backloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_backloginActionPerformed

    private void Regis_For_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regis_For_AdminActionPerformed
   
    }//GEN-LAST:event_Regis_For_AdminActionPerformed

    private void Regis_For_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regis_For_UserActionPerformed
       
    }//GEN-LAST:event_Regis_For_UserActionPerformed

    private void Regis_For_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regis_For_AdminMouseClicked

    }//GEN-LAST:event_Regis_For_AdminMouseClicked

    private void Combo_box_GENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_box_GENDERActionPerformed

    }//GEN-LAST:event_Combo_box_GENDERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new P_LOGIN().setVisible(true);
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_bottom;
    private javax.swing.JTextField BOX_ID2;
    private javax.swing.JTextField BOX_ID3;
    private javax.swing.JTextField BOX_ID4;
    private javax.swing.JTextField BOX_ID5;
    private javax.swing.JTextField BOX_ID6;
    private javax.swing.JTextField BOX_ID7;
    private javax.swing.JPasswordField BOX_PW;
    private javax.swing.JTextField BOX_REG_USER;
    private javax.swing.JTextField BOX_User;
    private javax.swing.JPanel BUTTON;
    private javax.swing.JButton B_EXIT;
    private javax.swing.JButton B_MINIMIZE;
    private javax.swing.JButton Button_CANCLE;
    private javax.swing.JButton Button_LOGIN;
    private javax.swing.JComboBox<String> Combo_box_GENDER;
    private javax.swing.JLabel GIF_0;
    private javax.swing.JPanel LOGIN_LAYER;
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel PIC_LEFT;
    private javax.swing.JPanel REGISTER_LAYER;
    private javax.swing.JCheckBox Regis_For_Admin;
    private javax.swing.JCheckBox Regis_For_User;
    private javax.swing.JPanel TAB_WINDOW;
    private javax.swing.JLabel TEXT_ADDRESS;
    private javax.swing.JLabel TEXT_AGE;
    private javax.swing.JLabel TEXT_CPASSWORD;
    private javax.swing.JLabel TEXT_EMAIL;
    private javax.swing.JLabel TEXT_EMAIL1;
    private javax.swing.JLabel TEXT_LNAME;
    private javax.swing.JLabel TEXT_LOGIN;
    private javax.swing.JLabel TEXT_LOGIN1;
    private javax.swing.JLabel TEXT_NAME;
    private javax.swing.JLabel TEXT_PASSWORD;
    private javax.swing.JLabel TEXT_USER;
    private javax.swing.JButton jButton_Register;
    private javax.swing.JButton jButton_backlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void Regis_For_User(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void Regis_For_Admin(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}

/*
class musicLogin{
    void playmusic(String musicLocation){
        
        try {
            File musicPath = new File(musicLocation);
            
            if(musicPath.exists()){
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
                clip.loop(clip.LOOP_CONTINUOUSLY);
                
                JOptionPane.showMessageDialog(null, "หยุดดดดดดดดดด");
                long clipTimePosition = clip.getMicrosecondPosition();
                clip.stop();
                
                JOptionPane.showMessageDialog(null, "ปลาหยุดดดดดดดดดดดดดดดด");
                clip.setMicrosecondPosition(clipTimePosition);
                clip.start();
                
                JOptionPane.showMessageDialog(null,"ยุทย?");
            }
            else{
                System.out.println("ERROR");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }
}
 */
//class PlayMusic {
//   
//}
